:recycle: Refactor peers action to work in unit tests
The problem was that activePeerSet action was importing a util (that was
importing store)
instead of dispatching action. This made the action not a pure function
and resulted in:
Uncaught TypeError: middleware is not a function